name: 'Deploy Logger'
description: 'Logs deployment metrics to Google Stackdriver'
author: 'velith'
inputs:
  github_api_key:
    description: 'Secret access token to use for Github API'
    required: true
  gcp_sa_key:
    descritpion: 'Secret key for a GCP service account'
    required: true
  branch:
    description: 'Branch deployment is made from'
    required: true
  log_name:
    description: 'Optional name for Stackdriver logs '
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'